### ISSUE TITLE
Rails 4.1 email preview takes a long time to load

### ISSUE THREAD

**Issue by mmustala** [fphilipe/premailer-rails#108]
Hi,

I just noticed that when using this gem with Rails 4.1 (4.1.0.rc2) and previewing an email it takes a really long time to load the view (a minute or something). I'm not sure if this issue should be fixed on the previewing side or on this side. I'm just posting what I saw.

An easy fix for this issue is to move `gem 'premailer-rails'` into production group. After that the previews will load normally. But you cannot get styles into emails which are actually delivered from the development environment.

**Comment by holoiii** [comment]
@mmustala's solution worked for me as well.

Thanks!

**Comment by moneypenny** [comment]
@mmustala's solution worked for me in Rails 4, development mode, with `asset_host` set in dev environment.

**Comment by karlingen** [comment]
Thanks @mmustala . Will this work in production as well?

**Comment by aleks** [comment]
Since this issue also takes place in Rails 4.2, i like to mention that you can solve this by using ActiveJob.

You need to add the "deliver_later" method to the Devise Mailer. You can do this by overriding ```send_devise_notification``` in you User Model (or AdminUser etc.):

```ruby
# app/models/user.rb
def send_devise_notification(notification, *args)
  devise_mailer.send(notification, self, *args).deliver_later
end
```
You don't need to add an ActiveJob Adapter to your ```config/application.rb``` but if it doesn't work without it, you could use a gem like Sidekiq or sucker_punch.

How to set the ActiveJob Adapter: http://guides.rubyonrails.org/active_job_basics.html#setting-the-backend

How to set sucker_punch as an ActiveJob Adapter: http://api.rubyonrails.org/classes/ActiveJob/QueueAdapters/SuckerPunchAdapter.html

I hope this solves the issue for most people, since disable locking in development seems like a *dirty* way in my opinion.

**Comment by karlingen** [comment]
Or if using sidekiq: https://github.com/mperham/sidekiq/wiki/Devise

**Comment by garyfoster** [comment]
As soon as I added config.action_mailer.asset_host to my config, the hang (which is actually a long delay) occurs in both dev and prod. I only added that config so I can add a url to an image in my asset pipeline but I can workaround that for now, but would be nice to know if there is a clean solution to this.

**Comment by divoxx** [comment]
I just found this thread, which is not really the problem I'm having but I have a guess about what's happening here: If you're delivering the email inside a request/response cycle, it could be that it's hitting the webapp in a loopback which can cause a deadlock if the request hits the same process and have to wait for the current request to finish.

**Comment by divoxx** [comment]
I identified and fixed the bug causing these problems, including mine. See https://github.com/fphilipe/premailer-rails/pull/140

**Comment by davidbobeck** [comment]
I am using 1.8.2 and have run into a problem that resembles what I've read about here.  I was able to work around the hang/timeout by doing this ...

    Thread.new do
      AccountNotifications.some_email(some_arg, some_other_arg).deliver_now
    end
 
If this is crazy silly .. someone please let me know.

**Comment by anduong** [comment]
I ran into this issue and the solution proposed by @mmustala and @suweller worked for me. Thanks! :+1: 

However, does anyone know the reason why it happens? Any idea @fphilipe?

**Comment by fphilipe** [comment]
Is this still an issue? This usually happens when you hard code the CSS URL instead of using the `stylesheet_link` helper, leading premailer-rails to request the file from the local server, which is already busy responding to the preview, resulting in a dead lock. Please check the example app.

**Comment by suweller** [comment]
I no longer work on nor have access to the application in which the problem occurred, but it may very well still exist. If I remember correctly we wanted inline `css`, in order to support a wider range of mail clients. Correct me if I'm wrong, but you're suggesting creating a link tag pointing to the stylesheet (`<link rel='stylesheet' href='...' />`) instead of a style tag embedding the stylesheet (`<style>...</style>`)

**Comment by fphilipe** [comment]
@suweller No, I'm suggesting to use the [`stylesheet_link_tag`](http://api.rubyonrails.org/classes/ActionView/Helpers/AssetTagHelper.html#method-i-stylesheet_link_tag) helper.

**Comment by suweller** [comment]
I may have not been entirely clear. I meant that the `stylesheet_link_tag` helper *creates* a `<link>` tag *linking* to the content of the css, while I intended to make a `<style>` tag *embedding* the content of the css file.

**Comment by anduong** [comment]
@fphilipe: I have tried `stylesheet_link_tag` and it works. Thanks :+1:
