### ISSUE TITLE
AssetPiplineLoader#file_name seems to create the wrong  for Rails 4+ Asset Pipline paths

### ISSUE THREAD

**Issue by SimonKaluza** [fphilipe/premailer-rails#115]
The AssetPipelineLoader calls :Rails.application.assets.find_asset with the wrong shortened pathname (it includes subdirectories, which will return nil and thus not be able to find the appropriate stylesheet).

This temporary monkeypatch seems to resolve the issue:

```
class Premailer
  module Rails
    module CSSLoaders
      module AssetPipelineLoader
        extend self
        
        def file_name(url)
          temp_path = URI(url).path
          .sub("#{::Rails.configuration.assets.prefix}/", '')
          .sub(/-\h{32}\.css$/, '.css').sub('/stylesheets/', '')
        end
        
      end
    end
  end
end
```

**Comment by ondrejbartas** [comment]
Confirming same issue with rails 4.2.0.

When added `.sub('/stylesheets', '')` it was working correctly.

Problem is that on all non production environments it is working but in production `find_assets` work differently, because `stylesheet_link_tag` is adding `/stylesheets` as prefix for assets. I tried to precompile `mailer.sass` which I am using as stylesheet, but find_asset  could not find any of them.

**Comment by fphilipe** [comment]
This should be fixed I think.
