### ISSUE TITLE
= and 3D being injected into my template.

### ISSUE THREAD

**Issue by espinet** [fphilipe/premailer-rails#186]
When my email is delivered, every `=` is replaced with `=3D`. Also, at the 73rd character, an the line is split into two lines with a trailing `=`. None of my styles get inlined. I've tried using <link... /> and <style>...</style> but the same thing happens.

Gemfile is using the following...
actionmailer (5.0.0.1)
nokogiri (1.7.1)
premailer (1.10.2)
premailer-rails (1.9.5)

This is what my email is outputting. Any idea whats wrong? Can I provide any more details to help debug?
```
Date: Mon, 10 Apr 2017 15:29:54 -0400
From: Testing <support@test.com>
To: engineering@test.com
Message-ID: <58ebdd32dd36c_2bc63fd294919bcc66854@My-MacBook-Air.local.mail>
Subject: Notifications
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<html>
  <head>
    <link rel=3D"stylesheet" type=3D"text/css" href=3D"marketing_mail.css=
" />
  </head>
  <body>
    <table>
  <tr class=3D"logo">
    <th colspan=3D"2"><img src=3D"https://s3.amazonaws.com/testimag-stati=
c/images/logos/logo-cropped-11.png" alt=3D"Logo cropped 11" /></=
th>
... rest of email excluded for brevity
```

**Comment by fphilipe** [comment]
This is because of the `Content-Transfer-Encoding: quoted-printable`, which uses `=xx` for special characters and thus escapes `=` with `=3D`. I think this per se is fine. If you look at that email in a mail client, it should render normally.

Having said that, it looks like the problem is that the CSS is not being inlined. Is the `marketing_mail.css` configured to be compiled by the asset pipeline?

I suggest you take a look at the example app in this repo and gradually tweak it to get what you want. This might help you in finding what the problem is.

**Comment by espinet** [comment]
Looks like it works. Not sure why it couldn't pull a url from the same rails project and use that. From the way I interpreted the documentation, it said it could. Putting it in the asset pipeline worked.

Thanks.
