### ISSUE TITLE
Undefined method find_sources for Sprockets::Manifest

### ISSUE THREAD

**Issue by AnrichVS** [fphilipe/premailer-rails#211]
The changes made during commit 1901dcffa381287c09a981e39a352829fb998502 cause the following error:

```
undefined method `find_sources' for #<Sprockets::Manifest:0x0055d9374853d0>
Did you mean?  find_asset
```

The specific line where this error occurs: `lib/premailer/rails/css_loaders/asset_pipeline_loader.rb:11`

I will probably create a pull request to fix this later today.

**Comment by jakepark** [comment]
Commit 1901dcf introduced a dependency on Sprockets::Manifest#find_sources.

sprockets version 2.x does not have Sprockets::Manifest#find_sources.

can confirm, downgrading to premailer-rails v1.9.7 prevents this error.

**Comment by fphilipe** [comment]
For my understanding, how come are you using sprockets 2? Is it hard coded? Are you using rails and if so, which version?

**Comment by jakepark** [comment]
From my project's gemfile:

ruby '2.3.4'
gem 'rails', '4.2.8'
gem 'sprockets', '~> 2.11.0'

**Comment by fphilipe** [comment]
@jakepark what sprockets-rails version do you have?

**Comment by jakepark** [comment]
from bundle show, not specified in gemfile:
sprockets-rails (2.3.3)

**Comment by fphilipe** [comment]
Could you try to simply `bundle update sprockets`? Your sprocket-rails version has a constraint `< 4.0` on sprockets.

Can you post you Gemfile.lock?

**Comment by jakepark** [comment]
Running bundle update sprockets has no change in gemfile lock.
```
Gemfile lock with relevant gems and dependencies:
activeadmin (1.0.0)
  arbre (>= 1.1.1)
  bourbon
  coffee-rails
  formtastic (~> 3.1)
  formtastic_i18n
  inherited_resources (~> 1.7)
  jquery-rails
  jquery-ui-rails
  kaminari (>= 0.15, < 2.0)
  railties (>= 4.2, < 5.2)
  ransack (~> 1.3)
  sass-rails
  sprockets (< 4.1)
  
angular-rails-templates (0.2.0)
  railties (>= 3.1)
  sprockets (~> 2)
  tilt
  
rails (4.2.8)
  actionmailer (= 4.2.8)
  actionpack (= 4.2.8)
  actionview (= 4.2.8)
  activejob (= 4.2.8)
  activemodel (= 4.2.8)
  activerecord (= 4.2.8)
  activesupport (= 4.2.8)
  bundler (>= 1.3.0, < 2.0)
  railties (= 4.2.8)
  sprockets-rails
  
sass-rails (5.0.4)
  railties (>= 4.0.0, < 5.0)
  sass (~> 3.1)
  sprockets (>= 2.8, < 4.0)
  sprockets-rails (>= 2.0, < 4.0)
  tilt (>= 1.1, < 3)
  
sprockets (2.11.3)
  hike (~> 1.2)
  multi_json (~> 1.0)
  rack (~> 1.0)
  tilt (~> 1.1, != 1.3.0)
sprockets-rails (2.3.3)
  actionpack (>= 3.0)
  activesupport (>= 3.0)
  sprockets (>= 2.8, < 4.0)
```

**Comment by fphilipe** [comment]
Your culprit is `angular-rails-templates`, which depends on `sprockets (~> 2)`.

Well, there's not much I can do. If premailer-rails would specify a hard dependency on `sprockets >= 3.0`, you would not be able to install the newest version. Thus, the only solution is to use premailer-rails < 1.10 or upgrade your sprockets version.

**Comment by jakepark** [comment]
OK thanks, using the previous version as described.

**Comment by JustAHappyKid** [comment]
Why _not_ make `premailer-rails` explicitly depend on `sprockets >= 3.0`? ...Seems to be broken otherwise; might save a few headaches.

**Comment by jakepark** [comment]
@JustAHappyKid I think the idea of semvar is to prevent breaking changes to downstream users who started using the published API prior to upgraded dependencies upstream.

Which is why I was mentioned when and where the commit dependency started breaking for my use case and the solution I am using. 

Because I sure as hell forgot what the heck I did to make things work. It's easy to suggest upgrading dependencies but really no business case to do so if things are already working well enough.

**Comment by hammerdr** [comment]
Definitely agree that sprockets >= 3.0 needs to be explicit, this was an unexpected error found during a rails upgrade

**Comment by dramalho** [comment]
just had this bite me, `sprockets > 3.0` should absolutely be in the `gemspec` file, what's the point of being able to upgrade version only to have it break - hopefully break your specs, but it can always break your app
